name: build

on:
  push:
    branches: 'main'

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    if: github.repository == 'gtm-nayan/svelte-yafal'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6

      - name: setup node
        run: pnpm env use --global lts

      - name: Install deps
        run: pnpm i

      - name: build
        env:
          BASE_PATH: '/svelte-yafal'
        run: |
          pnpm build
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
